In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('downloads/Price.csv')

In [3]:
df.head()

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,3/10/2025,132,NIMB,Nepal Investment Mega Bank Limited,222.0,226.0,216.2,218.0,207706.0,45230018.4,218.0,295.0,147.4,2025-03-10T14:59:25.482943,218,410.0,217.75,NaN
1,2,3/10/2025,137,EBL,Everest Bank Limited,629.9,630.0,615.3,621.8,28345.0,17561733.5,618.0,790.0,487.3,2025-03-10T14:59:56.568157,621.8,147.0,619.57,NaN
2,3,3/10/2025,139,NICA,NIC Asia Bank Ltd.,379.8,393.5,379.8,382.0,51563.0,19812899.6,387.5,573.0,341.6,2025-03-10T14:59:58.298049,382,353.0,384.24,NaN
3,4,3/10/2025,140,MBL,Machhapuchhre Bank Limited,234.0,235.8,230.0,232.0,68335.0,15866485.1,234.0,295.0,157.8,2025-03-10T14:59:56.612832,232,215.0,232.18,NaN
4,5,3/10/2025,142,KBL,Kumari Bank Limited,210.0,215.0,210.0,211.0,195478.0,41403265.2,211.4,272.9,129.6,2025-03-10T14:59:47.495057,211,572.0,211.80,NaN

In [4]:
df.shape

(311, 19)

In [5]:
df.isna().sum()

Id                            0
Business Date                 0
Security Id                   0
Symbol                        0
Security Name                 0
Open Price                    0
High Price                    0
Low Price                     0
Close Price                   0
Total Traded Quantity         0
Total Traded Value            0
Previous Day Close Price      0
Fifty Two Week High           0
Fifty Two Week Low            0
Last Updated Time             0
Last Updated Price            0
Total Trades                  0
Average Traded Price          0
Market Capitalization       309
dtype: int64

In [6]:
script=df['Symbol']

In [7]:
script

0         NIMB
1          EBL
2         NICA
3          MBL
4          KBL
        ...
306        KSY
307     SARBTM
308    NIMBD90
309    NIBLSTF
310      MNMF1
Name: Symbol, Length: 311, dtype: object

In [8]:
df['Close Price'] = df['Close Price'].astype(float)

In [9]:
(df['Close Price'].dtype)

dtype('float64')

In [10]:
mutual_f=df[df['Close Price']<20]

In [11]:
Remaining=df[~(df['Close Price']< 20)]

In [12]:
Remaining

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,3/10/2025,132,NIMB,Nepal Investment Mega Bank Limited,222.0,226.0,216.2,218.0,207706.0,45230018.4,218.0,295.0,147.4,2025-03-10T14:59:25.482943,218,410.0,217.75,NaN
1,2,3/10/2025,137,EBL,Everest Bank Limited,629.9,630.0,615.3,621.8,28345.0,17561733.5,618.0,790.0,487.3,2025-03-10T14:59:56.568157,621.8,147.0,619.57,NaN
2,3,3/10/2025,139,NICA,NIC Asia Bank Ltd.,379.8,393.5,379.8,382.0,51563.0,19812899.6,387.5,573.0,341.6,2025-03-10T14:59:58.298049,382,353.0,384.24,NaN
3,4,3/10/2025,140,MBL,Machhapuchhre Bank Limited,234.0,235.8,230.0,232.0,68335.0,15866485.1,234.0,295.0,157.8,2025-03-10T14:59:56.612832,232,215.0,232.18,NaN
4,5,3/10/2025,142,KBL,Kumari Bank Limited,210.0,215.0,210.0,211.0,195478.0,41403265.2,211.4,272.9,129.6,2025-03-10T14:59:47.495057,211,572.0,211.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,302,3/10/2025,9218,TVCL,Trishuli Jal Vidhyut Company Limited,575.0,596.0,550.0,550.0,20827.0,11766505.5,565.5,697.0,431.0,2025-03-10T14:59:52.543994,550,200.0,564.96,NaN
303,304,3/10/2025,9225,VLUCL,Vision Lumbini Urja Company Limited,714.5,740.0,705.0,711.0,25795.0,18505670.8,727.0,816.0,445.1,2025-03-10T14:59:59.146924,711,241.0,717.41,NaN
304,305,3/10/2025,9233,NWCL,Nepal Warehousing Company Limited,1035.0,1050.0,1007.9,1015.0,8929.0,9126730.5,1025.0,1264.0,678.0,2025-03-10T14:59:57.98133,1015,170.0,1022.14,NaN
307,308,3/10/2025,9242,SARBTM,Sarbottam Cement Limited,883.3,883.3,843.0,843.0,51793.0,44111789.4,866.0,1083.0,556.0,2025-03-10T14:59:59.005218,843,409.0,851.69,NaN
308,309,3/10/2025,9243,NIMBD90,10% NIMB Debenture 2090,1131.0,1131.0,1131.0,1131.0,30.0,33930.0,1131.9,1251.0,999.6,2025-03-10T12:06:59.822009,1131,1.0,1131.00,NaN

In [13]:
debenture_ = Remaining[Remaining['Security Name'].str.contains('debenture', case=False)]

In [14]:
debenture_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
135,136,3/10/2025,2825,NICAD85/86,10% NIC Asia Debenture 2085/86,1070.3,1070.3,1070.3,1070.3,25.0,26757.5,1083.0,1175.0,1000.0,2025-03-10T14:56:37.588547,1070.3,1.0,1070.30,NaN
136,137,3/10/2025,2828,SAND2085,10% Sanima Bank Limited Debenture,1078.0,1078.0,1078.0,1075.5,25.0,26937.5,1078.0,1256.6,1028.0,2025-03-10T11:35:18.10163,1075.5,2.0,1077.50,NaN
143,144,3/10/2025,2869,NICAD8283,11% NIC Asia Debenture 082/83,1145.0,1145.0,1130.0,1130.0,29.0,32843.9,1145.0,1262.7,1032.5,2025-03-10T14:07:49.353234,1130,3.0,1132.54,NaN
145,146,3/10/2025,2879,LBLD86,10% Laxmi Bank Debenture 2086,1080.1,1080.1,1080.0,1080.0,75.0,81005.0,1075.2,1135.0,985.4,2025-03-10T14:44:07.478831,1080,3.0,1080.06,NaN
148,149,3/10/2025,2890,SBIBD86,10% Nepal SBI Bank Debenture 2086,1077.2,1077.2,1070.0,1070.0,225.0,241181.5,1078.1,1154.9,1000.0,2025-03-10T14:57:32.304649,1070,9.0,1071.91,NaN
159,160,3/10/2025,2932,MFLD85,9.5% Manjushree Finance Limited Debenture 2085,1063.0,1063.0,1062.0,1062.0,379.0,402677.0,1062.0,1102.0,948.8,2025-03-10T14:57:32.93084,1062,6.0,1062.47,NaN
165,166,3/10/2025,4959,NBLD87,8.5% Nepal Bank Debenture 2087,1026.0,1026.0,1026.0,1026.0,25.0,25650.0,1025.0,1073.0,900.0,2025-03-10T12:39:59.917653,1026,1.0,1026.00,NaN
166,167,3/10/2025,4961,BOKD86,8.5% BOK Debenture 2086,1025.0,1025.0,1025.0,1025.1,10.0,10251.0,1025.0,1080.0,901.2,2025-03-10T12:20:29.162094,1025.1,2.0,1025.10,NaN
185,186,3/10/2025,8097,PBD88,10% Prime Debenture 2088,1092.0,1092.0,1092.0,1092.0,25.0,27300.0,1095.0,1219.7,999.0,2025-03-10T11:35:16.089526,1092,1.0,1092.00,NaN
191,192,3/10/2025,8116,PBD84,10.15% Prime Debenture 2084,1070.0,1070.0,1066.0,1066.0,100.0,106660.0,1064.5,1123.0,1000.0,2025-03-10T13:45:40.586193,1066,2.0,1066.60,NaN
192,193,3/10/2025,8119,EBLD85,10.50% Everest Bank Limited Debenture 2085,1117.4,1117.4,1117.4,1117.4,25.0,27935.0,1121.4,1178.0,1010.0,2025-03-10T12:31:30.052079,1117.4,1.0,1117.40,NaN
211,212,3/10/2025,2850,NMBD2085,10 % NMB DEBENTURE 2085,1077.1,1077.1,1076.0,1076.0,75.0,80747.0,1078.0,1135.0,999.0,2025-03-10T14:46:23.39928,1076,4.0,1076.62,NaN
213,214,3/10/2025,2878,SRBLD83,10.25% Sunrise Bank Debenture 2083,1043.5,1043.5,1037.3,1037.3,100.0,103962.5,1050.0,1152.6,1005.1,2025-03-10T11:14:53.37097,1037.3,5.0,1039.62,NaN
215,216,3/10/2025,2882,ICFCD83,12% ICFC Finance Limited Debenture 2083,1200.0,1200.0,1195.0,1195.0,650.0,778750.0,1205.0,1325.0,1112.0,2025-03-10T14:11:33.144073,1195,3.0,1198.07,NaN
216,217,3/10/2025,2885,KBLD86,10.25% KBL Debenture 2086,1105.0,1105.0,1105.0,1105.0,125.0,138125.0,1120.0,1257.4,1008.0,2025-03-10T14:39:20.892609,1105,1.0,1105.00,NaN
217,218,3/10/2025,2889,CIZBD86,10.25% Citizens Bank Debenture 2086,1100.1,1114.0,1100.1,1114.0,125.0,138902.5,1114.8,1147.2,1000.3,2025-03-10T13:39:11.28997,1114,3.0,1111.22,NaN
221,222,3/10/2025,2904,PBLD84,10% Prabhu Bank Debenture 2084,1075.0,1075.0,1075.0,1075.0,250.0,268750.0,1075.0,1130.0,997.0,2025-03-10T12:46:34.456923,1075,3.0,1075.00,NaN
224,225,3/10/2025,4948,KSBBLD87,9% Kamana Sewa Bikas Bank Limited Debenture 2087,1045.0,1045.0,1045.0,1045.0,200.0,209000.0,1065.0,1102.6,906.2,2025-03-10T14:55:58.548912,1045,2.0,1045.00,NaN
227,228,3/10/2025,4962,PBLD87,8.5% Prabhu Bank Debenture 2087,1022.1,1022.1,1022.1,1022.1,25.0,25552.5,1030.0,1080.0,900.8,2025-03-10T14:04:42.695854,1022.1,1.0,1022.10,NaN
229,230,3/10/2025,6984,PBD85,8.75 % Prime Debenture 2085,1035.0,1035.0,1035.0,1035.0,150.0,155250.0,1035.0,1080.0,903.2,2025-03-10T14:34:41.604964,1035,4.0,1035.00,NaN
256,257,3/10/2025,9249,ICFCD88,9% ICFC Finance Limited Debenture 2088,1078.0,1078.0,1045.0,1046.1,325.0,341122.0,1100.0,1100.0,1000.0,2025-03-10T14:56:46.686237,1046.1,14.0,1049.60,NaN
257,258,3/10/2025,6985,SDBD87,Shangri-la Development Bank Debenture 2087,1045.1,1045.5,1045.1,1045.1,125.0,130657.5,1045.0,1114.0,905.0,2025-03-10T14:38:29.313932,1045.1,3.0,1045.26,NaN
258,259,3/10/2025,8003,RBBD83,8.5% RBBL Debenture 2083,1016.3,1030.0,1015.0,1029.8,625.0,640250.0,1020.0,1062.0,946.5,2025-03-10T14:56:47.335061,1029.8,6.0,1024.40,NaN
262,263,3/10/2025,8027,NBLD85,Nabil Debenture 2085,1025.0,1025.0,1025.0,1025.0,25.0,25625.0,1020.0,1060.0,899.1,2025-03-10T13:41:03.483249,1025,1.0,1025.00,NaN
263,264,3/10/2025,8033,GBBD85,Garima Debenture,2085.0,1030.0,1030.0,1025.0,1026.5,126.0,129389.0,1023.0,1090.3,906.2,2025-03-10T14:49:02.601738,1026.5,4.00,1026.89
267,268,3/10/2025,8068,CCBD88,Century Debenture 2088,1122.5,1122.5,1120.5,1120.5,30.0,33645.0,1140.0,1250.0,996.1,2025-03-10T11:14:09.625939,1120.5,2.0,1121.50,NaN
271,272,3/10/2025,8098,SBLD89,10.75% SBL Debenture 2089,1146.6,1146.6,1146.6,1146.6,30.0,34398.0,1170.0,1247.0,1000.0,2025-03-10T12:46:32.858305,1146.6,1.0,1146.60,NaN
274,275,3/10/2025,8110,SBID83,10.25% Nepal SBI Bank Debenture 2083,1065.0,1065.0,1065.0,1065.0,50.0,53250.0,1057.0,1147.4,1008.5,2025-03-10T13:44:45.404951,1065,1.0,1065.00,NaN
308,309,3/10/2025,9243,NIMBD90,10% NIMB Debenture 2090,1131.0,1131.0,1131.0,1131.0,30.0,33930.0,1131.9,1251.0,999.6,2025-03-10T12:06:59.822009,1131,1.0,1131.00,NaN

In [15]:
debenture_.shape

(29, 19)

In [16]:
ordinary_S= Remaining[~Remaining['Security Name'].str.contains('Debenture', case=False)]

In [17]:
ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,3/10/2025,132,NIMB,Nepal Investment Mega Bank Limited,222.0,226.0,216.2,218.0,207706.0,45230018.4,218.0,295.0,147.4,2025-03-10T14:59:25.482943,218,410.0,217.75,NaN
1,2,3/10/2025,137,EBL,Everest Bank Limited,629.9,630.0,615.3,621.8,28345.0,17561733.5,618.0,790.0,487.3,2025-03-10T14:59:56.568157,621.8,147.0,619.57,NaN
2,3,3/10/2025,139,NICA,NIC Asia Bank Ltd.,379.8,393.5,379.8,382.0,51563.0,19812899.6,387.5,573.0,341.6,2025-03-10T14:59:58.298049,382,353.0,384.24,NaN
3,4,3/10/2025,140,MBL,Machhapuchhre Bank Limited,234.0,235.8,230.0,232.0,68335.0,15866485.1,234.0,295.0,157.8,2025-03-10T14:59:56.612832,232,215.0,232.18,NaN
4,5,3/10/2025,142,KBL,Kumari Bank Limited,210.0,215.0,210.0,211.0,195478.0,41403265.2,211.4,272.9,129.6,2025-03-10T14:59:47.495057,211,572.0,211.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,301,3/10/2025,9217,MMKJL,Mathillo Mailun Khola Jalvidhyut Limited,736.9,745.0,700.1,715.0,17007.0,12170870.7,722.5,890.4,395.0,2025-03-10T14:59:58.805061,715,171.0,715.63,NaN
301,302,3/10/2025,9218,TVCL,Trishuli Jal Vidhyut Company Limited,575.0,596.0,550.0,550.0,20827.0,11766505.5,565.5,697.0,431.0,2025-03-10T14:59:52.543994,550,200.0,564.96,NaN
303,304,3/10/2025,9225,VLUCL,Vision Lumbini Urja Company Limited,714.5,740.0,705.0,711.0,25795.0,18505670.8,727.0,816.0,445.1,2025-03-10T14:59:59.146924,711,241.0,717.41,NaN
304,305,3/10/2025,9233,NWCL,Nepal Warehousing Company Limited,1035.0,1050.0,1007.9,1015.0,8929.0,9126730.5,1025.0,1264.0,678.0,2025-03-10T14:59:57.98133,1015,170.0,1022.14,NaN
307,308,3/10/2025,9242,SARBTM,Sarbottam Cement Limited,883.3,883.3,843.0,843.0,51793.0,44111789.4,866.0,1083.0,556.0,2025-03-10T14:59:59.005218,843,409.0,851.69,NaN

In [18]:
shl_=ordinary_S[ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]

In [19]:
shl_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
6,7,3/10/2025,147,SHL,Soaltee Hotel Limited,499.0,503.0,490.0,493.3,44839.0,22281915.4,498.0,636.5,416.5,2025-03-10T14:59:22.648174,493.3,170.0,496.93,NaN

In [20]:
net_ordinary_S=ordinary_S[~ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]

In [21]:
net_ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,3/10/2025,132,NIMB,Nepal Investment Mega Bank Limited,222.0,226.0,216.2,218.0,207706.0,45230018.4,218.0,295.0,147.4,2025-03-10T14:59:25.482943,218,410.0,217.75,NaN
1,2,3/10/2025,137,EBL,Everest Bank Limited,629.9,630.0,615.3,621.8,28345.0,17561733.5,618.0,790.0,487.3,2025-03-10T14:59:56.568157,621.8,147.0,619.57,NaN
2,3,3/10/2025,139,NICA,NIC Asia Bank Ltd.,379.8,393.5,379.8,382.0,51563.0,19812899.6,387.5,573.0,341.6,2025-03-10T14:59:58.298049,382,353.0,384.24,NaN
3,4,3/10/2025,140,MBL,Machhapuchhre Bank Limited,234.0,235.8,230.0,232.0,68335.0,15866485.1,234.0,295.0,157.8,2025-03-10T14:59:56.612832,232,215.0,232.18,NaN
4,5,3/10/2025,142,KBL,Kumari Bank Limited,210.0,215.0,210.0,211.0,195478.0,41403265.2,211.4,272.9,129.6,2025-03-10T14:59:47.495057,211,572.0,211.80,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,301,3/10/2025,9217,MMKJL,Mathillo Mailun Khola Jalvidhyut Limited,736.9,745.0,700.1,715.0,17007.0,12170870.7,722.5,890.4,395.0,2025-03-10T14:59:58.805061,715,171.0,715.63,NaN
301,302,3/10/2025,9218,TVCL,Trishuli Jal Vidhyut Company Limited,575.0,596.0,550.0,550.0,20827.0,11766505.5,565.5,697.0,431.0,2025-03-10T14:59:52.543994,550,200.0,564.96,NaN
303,304,3/10/2025,9225,VLUCL,Vision Lumbini Urja Company Limited,714.5,740.0,705.0,711.0,25795.0,18505670.8,727.0,816.0,445.1,2025-03-10T14:59:59.146924,711,241.0,717.41,NaN
304,305,3/10/2025,9233,NWCL,Nepal Warehousing Company Limited,1035.0,1050.0,1007.9,1015.0,8929.0,9126730.5,1025.0,1264.0,678.0,2025-03-10T14:59:57.98133,1015,170.0,1022.14,NaN
307,308,3/10/2025,9242,SARBTM,Sarbottam Cement Limited,883.3,883.3,843.0,843.0,51793.0,44111789.4,866.0,1083.0,556.0,2025-03-10T14:59:59.005218,843,409.0,851.69,NaN

In [22]:
mutual_f

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
110,111,3/10/2025,2770,SEF,Siddhartha Equity Fund,10.08,10.08,9.76,9.80,71651.0,708792.78,9.90,10.49,7.42,2025-03-10T14:45:07.26347,9.8,9.0,9.89,NaN
138,139,3/10/2025,2835,NBF2,NABIL BALANCED FUND-2,9.50,9.60,9.50,9.58,13419.0,128434.98,9.60,10.63,7.65,2025-03-10T14:52:46.435782,9.58,12.0,9.57,NaN
142,143,3/10/2025,2867,NMB50,NMB 50,10.35,10.45,10.13,10.33,19900.0,206082.50,10.35,12.54,8.95,2025-03-10T14:42:24.331865,10.33,16.0,10.35,NaN
144,145,3/10/2025,2877,SFMF,Sunrise First Mutual Fund,10.20,10.25,10.20,10.20,6720.0,68635.00,10.20,11.99,9.22,2025-03-10T13:55:43.445588,10.2,5.0,10.21,NaN
156,157,3/10/2025,2923,SLCF,Sanima Large Cap Fund,9.28,9.47,9.28,9.47,4420.0,41437.40,9.45,10.60,7.40,2025-03-10T14:53:33.100548,9.47,14.0,9.37,NaN
160,161,3/10/2025,2933,KEF,Kumari Equity Fund,8.85,9.00,8.82,8.82,16025.0,141926.25,8.85,10.76,7.79,2025-03-10T14:49:39.361617,8.82,24.0,8.85,NaN
164,165,3/10/2025,4947,PSF,Prabhu Select Fund,10.01,10.20,10.01,10.10,53500.0,545294.00,9.98,11.10,8.34,2025-03-10T14:58:35.945305,10.1,31.0,10.19,NaN
168,169,3/10/2025,4967,NICSF,NIC Asia Select Fund 30,9.29,9.30,9.05,9.11,14255.0,129883.05,9.15,11.45,8.31,2025-03-10T14:57:55.093407,9.11,25.0,9.11,NaN
169,170,3/10/2025,4968,RMF1,RBB Mutual Fund 1,8.65,8.80,8.65,8.70,22800.0,198776.00,8.80,10.19,7.46,2025-03-10T14:41:40.44852,8.7,16.0,8.71,NaN
174,175,3/10/2025,8023,MMF1,Mega Mutual Fund -1,8.45,8.70,8.45,8.57,32049.0,274909.38,8.60,9.72,6.53,2025-03-10T14:56:52.589586,8.57,40.0,8.57,NaN
183,184,3/10/2025,8073,NICFC,NIC Asia Flexi CAP Fund,9.03,9.10,9.03,9.09,5150.0,46722.00,9.10,10.99,8.13,2025-03-10T14:56:38.744736,9.09,27.0,9.07,NaN
188,189,3/10/2025,8106,GIBF1,Global IME Balanced Fund-1,9.79,9.83,9.73,9.83,1150.0,11262.50,9.79,10.72,7.92,2025-03-10T14:57:29.153976,9.83,9.0,9.79,NaN
194,195,3/10/2025,8125,NSIF2,NMB Sulav Investment Fund - 2,10.19,10.42,10.19,10.42,2317.0,23710.74,10.37,12.47,8.65,2025-03-10T14:58:16.3844,10.42,13.0,10.23,NaN
197,198,3/10/2025,9139,SAGF,Sanima Growth Fund,9.55,9.55,9.37,9.37,1200.0,11298.00,9.55,10.93,8.37,2025-03-10T14:21:36.210173,9.37,5.0,9.41,NaN
212,213,3/10/2025,2862,CMF2,CITIZENS MUTUAL FUND 2,9.50,9.50,9.50,9.50,600.0,5700.00,9.60,10.68,7.65,2025-03-10T14:49:46.709694,9.5,2.0,9.50,NaN
220,221,3/10/2025,2902,LUK,Laxmi Unnati Kosh,9.60,9.61,9.60,9.61,600.0,5761.00,9.68,10.22,7.98,2025-03-10T14:40:49.055724,9.61,5.0,9.60,NaN
223,224,3/10/2025,2937,SBCF,Sunrise Bluechip Fund,9.14,9.33,9.14,9.20,35260.0,325145.00,9.22,10.04,7.34,2025-03-10T14:58:50.977824,9.2,24.0,9.22,NaN
225,226,3/10/2025,4949,NIBSF2,NIBL Samriddhi Fund -2,8.33,8.49,8.30,8.30,99700.0,831459.54,8.50,9.60,7.26,2025-03-10T14:50:32.619668,8.3,43.0,8.33,NaN
238,239,3/10/2025,9174,PRSF,Prabhu Smart Fund,10.07,10.45,10.07,10.45,3900.0,39945.70,10.25,11.30,8.21,2025-03-10T13:41:10.471775,10.45,14.0,10.24,NaN
240,241,3/10/2025,9178,RMF2,RBB Mutual Fund 2,9.02,9.10,9.02,9.02,600.0,5436.00,9.10,10.73,7.91,2025-03-10T14:31:11.236132,9.02,4.0,9.06,NaN
243,244,3/10/2025,9182,SIGS3,Siddhartha Investment Growth Scheme 3,9.82,10.00,9.68,9.81,1600.0,15773.00,9.82,10.81,7.86,2025-03-10T14:56:41.825449,9.81,10.0,9.85,NaN
255,256,3/10/2025,9248,GSY,Garima Samriddhi Yojana,9.20,9.20,9.06,9.13,10450.0,95392.00,9.30,10.00,8.80,2025-03-10T14:59:08.650841,9.13,60.0,9.12,NaN
260,261,3/10/2025,8024,NBF3,Nabil Balanced Fund-3,9.12,9.44,9.12,9.34,36077.0,332471.83,9.30,10.45,7.05,2025-03-10T14:58:16.431144,9.34,45.0,9.21,NaN
269,270,3/10/2025,8074,KDBY,Kumari Dhanabriddhi Yojana,9.47,9.55,9.29,9.36,22450.0,212953.00,9.65,11.00,8.26,2025-03-10T14:59:30.415245,9.36,53.0,9.48,NaN
286,287,3/10/2025,9154,SFEF,Sunrise Focused Equity Fund,9.19,9.26,9.19,9.26,1000.0,9244.00,9.30,10.66,7.54,2025-03-10T14:57:25.921199,9.26,5.0,9.24,NaN
290,291,3/10/2025,9191,C30MF,Citizens Super 30 Mutual Fund,8.85,8.92,8.80,8.80,10100.0,89557.00,8.95,10.92,8.13,2025-03-10T14:52:30.827787,8.8,8.0,8.86,NaN
294,295,3/10/2025,9198,LVF2,Laxmi Value Fund 2,9.28,9.41,9.28,9.35,2400.0,22470.00,9.41,10.01,7.50,2025-03-10T14:48:34.387408,9.35,19.0,9.36,NaN
302,303,3/10/2025,9221,H8020,Himalayan 80-20,10.19,10.20,10.08,10.20,1900.0,19284.00,10.38,10.83,8.36,2025-03-10T14:55:35.794163,10.2,15.0,10.14,NaN
305,306,3/10/2025,9236,NICGF2,NIC ASIA Growth Fund-2,8.60,8.62,8.60,8.60,1900.0,16351.00,8.59,9.79,7.32,2025-03-10T14:21:34.172734,8.6,12.0,8.60,NaN
306,307,3/10/2025,9241,KSY,Kumari Sabal Yojana,8.81,8.90,8.81,8.87,1800.0,15922.00,8.98,10.91,7.77,2025-03-10T14:57:57.361576,8.87,15.0,8.84,NaN
309,310,3/10/2025,9244,NIBLSTF,NIBL Stable Fund,8.40,8.50,8.33,8.38,1200.0,10070.00,8.47,10.55,7.95,2025-03-10T14:21:18.902755,8.38,12.0,8.39,NaN
310,311,3/10/2025,9245,MNMF1,Muktinath Mutual Fund 1,9.06,9.20,9.06,9.10,9700.0,88351.00,9.20,10.42,8.67,2025-03-10T14:41:08.30319,9.1,34.0,9.10,NaN

In [23]:
mutual_f.shape

(32, 19)

In [24]:
mutual_=mutual_f[['Symbol','Close Price']]

In [25]:
mutual_

      Symbol  Close Price
110      SEF         9.80
138     NBF2         9.58
142    NMB50        10.33
144     SFMF        10.20
156     SLCF         9.47
160      KEF         8.82
164      PSF        10.10
168    NICSF         9.11
169     RMF1         8.70
174     MMF1         8.57
183    NICFC         9.09
188    GIBF1         9.83
194    NSIF2        10.42
197     SAGF         9.37
212     CMF2         9.50
220      LUK         9.61
223     SBCF         9.20
225   NIBSF2         8.30
238     PRSF        10.45
240     RMF2         9.02
243    SIGS3         9.81
255      GSY         9.13
260     NBF3         9.34
269     KDBY         9.36
286     SFEF         9.26
290    C30MF         8.80
294     LVF2         9.35
302    H8020        10.20
305   NICGF2         8.60
306      KSY         8.87
309  NIBLSTF         8.38
310    MNMF1         9.10

In [26]:
ordinary_=net_ordinary_S[['Symbol','Close Price']]

In [27]:
ordinary_

     Symbol  Close Price
0      NIMB        218.0
1       EBL        621.8
2      NICA        382.0
3       MBL        232.0
4       KBL        211.0
..      ...          ...
300   MMKJL        715.0
301    TVCL        550.0
303   VLUCL        711.0
304    NWCL       1015.0
307  SARBTM        843.0

[249 rows x 2 columns]

In [89]:
def total(mutual_,ordinary_,shl_):
    i,j,k = 0,0,0
    for index, row in mutual_.iterrows():
        i += row['Close Price'] * 100
    for index, row in ordinary_.iterrows():
        j += row['Close Price'] * 10 
    for index, row in shl_.iterrows():
        k += row['Close Price'] * 100 
    
    return i,j,k

In [90]:
total(mutual_,ordinary_,shl_)

(29967.0, 3011108.0, 49330.0)

In [94]:
net_total=sum(total(mutual_,ordinary_,shl_))

In [95]:
net_total

3090405.0