In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('price_2025-05-15.csv', on_bad_lines='warn')

Skipping line 264: expected 19 fields, saw 20

In [3]:
df.head()

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2025-05-15,132,NIMB,Nepal Investment Mega Bank Limited,204.1,206.0,203.0,203.65,50873,10366419.8,204.22,295.0,149.2,2025-05-15T14:59:51.292124,204.0,264,203.77,69502.88
1,2,2025-05-15,135,SBI,Nepal SBI Bank Limited,380.0,382.0,374.4,375.83,19394,7321585.6,375.49,549.0,274.4,2025-05-15T14:59:51.776636,375.1,105,377.51,40962.31
2,3,2025-05-15,137,EBL,Everest Bank Limited,614.1,616.0,610.1,612.40,27168,16636243.8,613.82,790.0,502.5,2025-05-15T14:59:54.216232,612.9,149,612.34,79273.31
3,4,2025-05-15,140,MBL,Machhapuchhre Bank Limited,211.0,214.3,208.6,211.18,50649,10686668.0,211.55,295.0,164.2,2025-05-15T14:59:46.025472,212.9,180,210.99,24541.98
4,5,2025-05-15,141,LSL,Laxmi Sunrise Bank Limited,204.0,207.3,202.0,205.31,71921,14646562.0,204.52,300.0,147.7,2025-05-15T14:59:57.603135,206.0,253,203.64,49985.82

In [4]:
df.shape

(319, 19)

In [5]:
df.isna().sum()

Id                          0
Business Date               0
Security Id                 0
Symbol                      0
Security Name               0
Open Price                  0
High Price                  0
Low Price                   0
Close Price                 0
Total Traded Quantity       0
Total Traded Value          0
Previous Day Close Price    0
Fifty Two Week High         0
Fifty Two Week Low          0
Last Updated Time           0
Last Updated Price          0
Total Trades                0
Average Traded Price        0
Market Capitalization       2
dtype: int64

In [6]:
script=df['Symbol']

In [7]:
script

0         NIMB
1          SBI
2          EBL
3          MBL
4          LSL
        ...
314    NIBLSTF
315      MNMF1
316      CREST
317     NMBHF2
318       OMPL
Name: Symbol, Length: 319, dtype: object

In [8]:
(df['Open Price'].dtype)

dtype('float64')

In [9]:
mutual_f=df[df['Open Price']<20]

In [10]:
Remaining=df[~(df['Open Price']< 20)]

In [11]:
Remaining

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2025-05-15,132,NIMB,Nepal Investment Mega Bank Limited,204.1,206.0,203.0,203.65,50873,10366419.8,204.22,295.0,149.2,2025-05-15T14:59:51.292124,204.0,264,203.77,69502.88
1,2,2025-05-15,135,SBI,Nepal SBI Bank Limited,380.0,382.0,374.4,375.83,19394,7321585.6,375.49,549.0,274.4,2025-05-15T14:59:51.776636,375.1,105,377.51,40962.31
2,3,2025-05-15,137,EBL,Everest Bank Limited,614.1,616.0,610.1,612.40,27168,16636243.8,613.82,790.0,502.5,2025-05-15T14:59:54.216232,612.9,149,612.34,79273.31
3,4,2025-05-15,140,MBL,Machhapuchhre Bank Limited,211.0,214.3,208.6,211.18,50649,10686668.0,211.55,295.0,164.2,2025-05-15T14:59:46.025472,212.9,180,210.99,24541.98
4,5,2025-05-15,141,LSL,Laxmi Sunrise Bank Limited,204.0,207.3,202.0,205.31,71921,14646562.0,204.52,300.0,147.7,2025-05-15T14:59:57.603135,206.0,253,203.64,49985.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,312,2025-05-15,9246,GMLI,Guardian Micro Life Insurance Limited,2650.0,2675.0,2567.0,2589.03,48046,124455768.1,2648.22,2778.0,301.0,2025-05-15T14:59:51.869199,2589.1,611,2590.34,19417.72
312,314,2025-05-15,9249,ICFCD88,9% ICFC Finance Limited Debenture 2088,1090.0,1090.1,1090.0,1090.10,50,54502.5,1097.00,1116.0,1000.0,2025-05-15T11:42:29.189974,1090.1,2,1090.05,327.03
313,315,2025-05-15,9250,NMIC,Nepal Micro Insurance Company Limited,2050.0,2255.0,1960.0,2190.06,59233,125400472.5,2081.02,2703.3,302.3,2025-05-15T14:59:59.013712,2200.0,5466,2117.07,16425.45
316,318,2025-05-15,9252,CREST,Crest Micro Life Insurance Limited,2025.0,2228.0,1953.2,2151.20,88593,185884964.4,2066.15,2458.2,302.5,2025-05-15T14:59:57.942001,2130.0,8395,2098.19,16134.00
318,320,2025-05-15,9256,OMPL,Om Megashree Pharmaceuticals Limited,578.3,636.2,578.3,636.20,460,290351.0,578.40,636.2,270.0,2025-05-15T14:54:38.940539,636.2,46,631.19,3817.20

In [12]:
debenture_ = Remaining[Remaining['Security Name'].str.contains('debenture|bond', case=False)]

In [13]:
debenture_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
139,140,2025-05-15,2854,NBBD2085,10.25% NBBL Debenture 2085,1117.0,1117.0,1117.0,1117.4,2,2234.8,1117.00,1240.0,1051.0,2025-05-15T14:57:17.845014,1117.0,1,1117.40,2234.80
152,153,2025-05-15,2828,SAND2085,10% Sanima Bank Limited Debenture,1102.2,1102.2,1102.2,1102.2,25,27555.0,1105.00,1256.6,1028.0,2025-05-15T12:49:41.409269,1102.2,1,1102.20,2204.40
161,162,2025-05-15,2904,PBLD84,10% Prabhu Bank Debenture 2084,1115.1,1115.1,1115.1,1115.1,100,111510.0,1120.73,1130.0,1022.0,2025-05-15T14:31:36.563478,1115.1,1,1115.10,2230.20
169,170,2025-05-15,2866,MBLD2085,10.25% Machhapuchhre Bank Debenture 2085,1130.0,1130.0,1130.0,1130.0,25,28250.0,1125.90,1206.8,1030.2,2025-05-15T12:47:59.741568,1130.0,1,1130.00,3390.00
174,175,2025-05-15,2882,ICFCD83,12% ICFC Finance Limited Debenture 2083,1190.0,1190.0,1190.0,1190.0,200,238000.0,1208.00,1325.0,1165.0,2025-05-15T14:10:52.234313,1190.0,1,1190.00,238.00
175,176,2025-05-15,2883,GWFD83,12 % Goodwill Finance Limited Debenture 2083,1165.1,1165.1,1165.1,1167.9,3,3477.9,1165.10,1363.2,1140.0,2025-05-15T14:40:02.245749,1165.1,3,1159.30,291.98
176,177,2025-05-15,2890,SBIBD86,10% Nepal SBI Bank Debenture 2086,1117.3,1117.3,1117.2,1117.2,50,55862.5,1140.00,1160.0,1022.6,2025-05-15T12:08:19.198364,1117.2,2,1117.25,2272.26
187,188,2025-05-15,4962,PBLD87,8.5% Prabhu Bank Debenture 2087,1061.1,1061.1,1061.1,1061.1,25,26527.5,1050.10,1080.0,960.0,2025-05-15T11:25:08.64054,1061.1,1,1061.10,2811.91
189,190,2025-05-15,4969,MND84/85,Muktinath Debenture 2084/85,1067.7,1067.7,1067.7,1067.7,25,26692.5,1070.00,1100.0,950.9,2025-05-15T14:57:45.696326,1067.7,1,1067.70,1334.63
191,192,2025-05-15,7985,MBLD87,8.5% Machhapuchchhre Debenture 2087,1070.0,1070.0,1070.0,1070.0,8,8560.0,1070.00,1081.0,931.0,2025-05-15T14:56:49.559273,1070.0,2,1070.00,2411.24
192,193,2025-05-15,8004,GBILD86/87,Global IME Bank Limited Debenture 2086/87,1051.1,1051.1,1051.1,1054.3,2,2108.6,1051.10,1095.0,935.5,2025-05-15T14:28:04.536432,1051.1,1,1054.30,3162.90
198,199,2025-05-15,2931,NIBD84,8.5% Nepal Investment Bank Debenture 2084,1062.8,1062.8,1062.8,1062.8,32,34009.6,1042.00,1077.0,943.0,2025-05-15T12:10:24.273801,1062.8,1,1062.80,4251.20
201,202,2025-05-15,4948,KSBBLD87,9% Kamana Sewa Bikas Bank Limited Debenture 2087,1110.0,1110.0,1110.0,1110.0,46,51060.0,1095.10,1110.0,980.0,2025-05-15T13:46:31.94127,1110.0,3,1110.00,1110.00
202,203,2025-05-15,4959,NBLD87,8.5% Nepal Bank Debenture 2087,1070.1,1070.1,1070.1,1070.1,25,26752.5,1065.20,1082.2,916.0,2025-05-15T13:45:44.001706,1070.1,1,1070.10,3745.35
203,204,2025-05-15,4963,NMBD87/88,NMB Debenture 8.50% - 2087/88,1060.0,1060.0,1060.0,1060.0,25,26500.0,1060.00,1103.6,930.0,2025-05-15T11:21:29.809151,1060.0,1,1060.00,2120.00
207,208,2025-05-15,8020,JBBD87,Jyoti Bikash Bank Bond 2087,1100.0,1119.0,1100.0,1119.0,102,113950.0,1100.00,1119.0,965.0,2025-05-15T12:29:47.563592,1119.0,6,1117.15,1678.50
212,213,2025-05-15,8043,CBLD88,Civil Bank Debenture 2088,1131.0,1131.0,1131.0,1131.0,25,28275.0,1131.00,1254.2,1018.0,2025-05-15T11:24:38.701901,1131.0,1,1131.00,3393.00
217,218,2025-05-15,8098,SBLD89,10.75% SBL Debenture 2089,1275.0,1275.0,1275.0,1275.0,50,63750.0,1278.30,1278.3,1056.5,2025-05-15T14:41:03.83011,1275.0,1,1275.00,5100.00
221,222,2025-05-15,8110,SBID83,10.25% Nepal SBI Bank Debenture 2083,1100.0,1100.0,1078.1,1099.6,567,623055.7,1099.00,1147.4,1015.1,2025-05-15T14:08:42.185394,1099.6,3,1098.86,2640.67
222,223,2025-05-15,8116,PBD84,10.15% Prime Debenture 2084,1112.0,1112.0,1112.0,1112.0,10,11120.0,1095.00,1123.0,1000.0,2025-05-15T12:36:16.046539,1112.0,1,1112.00,NaN
232,233,2025-05-15,8068,CCBD88,Century Debenture 2088,1188.0,1188.0,1188.0,1188.0,150,178200.0,1165.00,1250.0,1049.1,2025-05-15T12:13:02.683604,1188.0,1,1188.00,2613.60
236,237,2025-05-15,8097,PBD88,10% Prime Debenture 2088,1145.2,1145.2,1145.2,1145.2,50,57260.0,1146.00,1219.7,1001.0,2025-05-15T14:00:01.037506,1145.2,2,1145.20,1994.81
242,243,2025-05-15,8119,EBLD85,10.50% Everest Bank Limited Debenture 2085,1112.0,1112.0,1112.0,1112.0,25,27800.0,1111.90,1200.0,1044.5,2025-05-15T13:05:40.11766,1112.0,1,1112.00,2224.00
276,278,2025-05-15,9231,CIZBD90,10% Citizens Bank Debenture 2090,1135.0,1135.0,1135.0,1135.0,25,28375.0,1142.00,1205.0,1000.0,2025-05-15T13:07:05.873295,1135.0,1,1135.00,3405.00
303,305,2025-05-15,9220,KBLD90,10% KBL Debenture 2090,1182.0,1182.0,1182.0,1182.0,35,41370.0,1173.00,1324.9,1000.0,2025-05-15T12:22:16.350724,1182.0,2,1182.00,5910.00
312,314,2025-05-15,9249,ICFCD88,9% ICFC Finance Limited Debenture 2088,1090.0,1090.1,1090.0,1090.1,50,54502.5,1097.00,1116.0,1000.0,2025-05-15T11:42:29.189974,1090.1,2,1090.05,327.03

In [14]:
debenture_.shape

(26, 19)

In [15]:
ordinary_S= Remaining[~Remaining['Security Name'].str.contains('Debenture|bond', case=False)]

In [16]:
ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2025-05-15,132,NIMB,Nepal Investment Mega Bank Limited,204.1,206.0,203.0,203.65,50873,10366419.8,204.22,295.0,149.2,2025-05-15T14:59:51.292124,204.0,264,203.77,69502.88
1,2,2025-05-15,135,SBI,Nepal SBI Bank Limited,380.0,382.0,374.4,375.83,19394,7321585.6,375.49,549.0,274.4,2025-05-15T14:59:51.776636,375.1,105,377.51,40962.31
2,3,2025-05-15,137,EBL,Everest Bank Limited,614.1,616.0,610.1,612.40,27168,16636243.8,613.82,790.0,502.5,2025-05-15T14:59:54.216232,612.9,149,612.34,79273.31
3,4,2025-05-15,140,MBL,Machhapuchhre Bank Limited,211.0,214.3,208.6,211.18,50649,10686668.0,211.55,295.0,164.2,2025-05-15T14:59:46.025472,212.9,180,210.99,24541.98
4,5,2025-05-15,141,LSL,Laxmi Sunrise Bank Limited,204.0,207.3,202.0,205.31,71921,14646562.0,204.52,300.0,147.7,2025-05-15T14:59:57.603135,206.0,253,203.64,49985.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,311,2025-05-15,9242,SARBTM,Sarbottam Cement Limited,869.9,885.0,838.0,843.89,136488,116179028.4,852.91,1060.0,696.8,2025-05-15T14:59:59.443201,838.0,471,851.20,41987.75
310,312,2025-05-15,9246,GMLI,Guardian Micro Life Insurance Limited,2650.0,2675.0,2567.0,2589.03,48046,124455768.1,2648.22,2778.0,301.0,2025-05-15T14:59:51.869199,2589.1,611,2590.34,19417.72
313,315,2025-05-15,9250,NMIC,Nepal Micro Insurance Company Limited,2050.0,2255.0,1960.0,2190.06,59233,125400472.5,2081.02,2703.3,302.3,2025-05-15T14:59:59.013712,2200.0,5466,2117.07,16425.45
316,318,2025-05-15,9252,CREST,Crest Micro Life Insurance Limited,2025.0,2228.0,1953.2,2151.20,88593,185884964.4,2066.15,2458.2,302.5,2025-05-15T14:59:57.942001,2130.0,8395,2098.19,16134.00
318,320,2025-05-15,9256,OMPL,Om Megashree Pharmaceuticals Limited,578.3,636.2,578.3,636.20,460,290351.0,578.40,636.2,270.0,2025-05-15T14:54:38.940539,636.2,46,631.19,3817.20

In [17]:
shl_=ordinary_S[ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]

In [18]:
shl_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
5,6,2025-05-15,147,SHL,Soaltee Hotel Limited,529.0,575.5,525.0,571.85,824999,461915510.4,529.25,636.5,416.5,2025-05-15T14:59:58.585295,573.0,2366,559.89,58435.22

In [19]:
net_ordinary_S=ordinary_S[~ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]

In [20]:
net_ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2025-05-15,132,NIMB,Nepal Investment Mega Bank Limited,204.1,206.0,203.0,203.65,50873,10366419.8,204.22,295.0,149.2,2025-05-15T14:59:51.292124,204.0,264,203.77,69502.88
1,2,2025-05-15,135,SBI,Nepal SBI Bank Limited,380.0,382.0,374.4,375.83,19394,7321585.6,375.49,549.0,274.4,2025-05-15T14:59:51.776636,375.1,105,377.51,40962.31
2,3,2025-05-15,137,EBL,Everest Bank Limited,614.1,616.0,610.1,612.40,27168,16636243.8,613.82,790.0,502.5,2025-05-15T14:59:54.216232,612.9,149,612.34,79273.31
3,4,2025-05-15,140,MBL,Machhapuchhre Bank Limited,211.0,214.3,208.6,211.18,50649,10686668.0,211.55,295.0,164.2,2025-05-15T14:59:46.025472,212.9,180,210.99,24541.98
4,5,2025-05-15,141,LSL,Laxmi Sunrise Bank Limited,204.0,207.3,202.0,205.31,71921,14646562.0,204.52,300.0,147.7,2025-05-15T14:59:57.603135,206.0,253,203.64,49985.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,311,2025-05-15,9242,SARBTM,Sarbottam Cement Limited,869.9,885.0,838.0,843.89,136488,116179028.4,852.91,1060.0,696.8,2025-05-15T14:59:59.443201,838.0,471,851.20,41987.75
310,312,2025-05-15,9246,GMLI,Guardian Micro Life Insurance Limited,2650.0,2675.0,2567.0,2589.03,48046,124455768.1,2648.22,2778.0,301.0,2025-05-15T14:59:51.869199,2589.1,611,2590.34,19417.72
313,315,2025-05-15,9250,NMIC,Nepal Micro Insurance Company Limited,2050.0,2255.0,1960.0,2190.06,59233,125400472.5,2081.02,2703.3,302.3,2025-05-15T14:59:59.013712,2200.0,5466,2117.07,16425.45
316,318,2025-05-15,9252,CREST,Crest Micro Life Insurance Limited,2025.0,2228.0,1953.2,2151.20,88593,185884964.4,2066.15,2458.2,302.5,2025-05-15T14:59:57.942001,2130.0,8395,2098.19,16134.00
318,320,2025-05-15,9256,OMPL,Om Megashree Pharmaceuticals Limited,578.3,636.2,578.3,636.20,460,290351.0,578.40,636.2,270.0,2025-05-15T14:54:38.940539,636.2,46,631.19,3817.20

In [21]:
mutual_f

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
120,121,2025-05-15,2770,SEF,Siddhartha Equity Fund,9.89,9.89,9.60,9.70,19400,188234.00,9.70,10.49,7.80,2025-05-15T14:25:46.758443,9.70,6,9.70,1455.00
136,137,2025-05-15,2835,NBF2,NABIL BALANCED FUND-2,9.90,10.05,9.52,9.97,3460,34287.00,9.71,10.63,8.00,2025-05-15T13:59:40.002037,9.97,13,9.90,1116.64
154,155,2025-05-15,2859,SIGS2,Siddhartha Investment Growth Scheme - 2,10.29,10.29,10.29,10.29,2000,20580.00,10.48,10.48,7.94,2025-05-15T14:57:04.378575,10.29,1,10.29,1234.80
155,156,2025-05-15,2862,CMF2,CITIZENS MUTUAL FUND 2,9.39,9.42,9.39,9.42,300,2822.00,9.41,10.68,8.00,2025-05-15T12:49:09.968121,9.42,3,9.40,527.52
156,157,2025-05-15,2863,NICBF,NIC Asia Balanced Fund,9.04,9.04,9.04,9.04,200,1808.00,9.09,10.50,8.38,2025-05-15T14:05:07.117613,9.04,1,9.04,682.52
159,160,2025-05-15,2902,LUK,Laxmi Unnati Kosh,9.60,9.79,9.55,9.73,2350,22730.00,9.62,10.22,8.16,2025-05-15T14:59:51.726237,9.79,7,9.67,635.00
167,168,2025-05-15,2923,SLCF,Sanima Large Cap Fund,9.61,9.80,9.61,9.80,9300,90242.50,9.64,10.60,7.84,2025-05-15T14:57:33.218167,9.80,16,9.70,1176.00
170,171,2025-05-15,2867,NMB50,NMB 50,10.60,10.81,10.60,10.81,265,2840.50,10.79,12.54,8.95,2025-05-15T14:33:08.262675,10.81,2,10.71,1351.25
171,172,2025-05-15,2877,SFMF,Sunrise First Mutual Fund,10.22,10.71,10.22,10.71,4075,42907.50,10.34,11.99,9.22,2025-05-15T13:53:35.881669,10.71,6,10.52,921.06
181,182,2025-05-15,2933,KEF,Kumari Equity Fund,8.86,9.10,8.86,9.10,3916,35250.60,9.03,10.76,7.91,2025-05-15T14:59:27.967246,9.10,10,9.00,910.00
183,184,2025-05-15,2937,SBCF,Sunrise Bluechip Fund,9.37,9.41,9.37,9.40,25365,238025.93,9.37,10.04,7.56,2025-05-15T14:59:25.067119,9.40,15,9.38,1175.00
184,185,2025-05-15,4947,PSF,Prabhu Select Fund,10.66,10.80,10.66,10.66,115215,1228986.00,10.64,11.10,8.36,2025-05-15T14:59:27.285531,10.66,27,10.66,1332.50
185,186,2025-05-15,4949,NIBSF2,NIBL Samriddhi Fund -2,8.06,8.21,8.06,8.19,22450,184131.00,8.20,9.60,7.53,2025-05-15T14:51:31.953396,8.19,12,8.20,1228.50
204,205,2025-05-15,4967,NICSF,NIC Asia Select Fund 30,9.08,9.10,9.05,9.08,1700,15423.00,9.23,11.45,8.31,2025-05-15T14:53:54.149282,9.08,10,9.07,1135.00
205,206,2025-05-15,4968,RMF1,RBB Mutual Fund 1,9.10,9.29,9.10,9.20,24600,227906.00,9.12,10.19,7.67,2025-05-15T14:53:37.974765,9.20,20,9.26,1150.00
208,209,2025-05-15,8024,NBF3,Nabil Balanced Fund-3,9.74,9.93,9.36,9.59,27010,256655.00,9.55,10.45,7.08,2025-05-15T14:52:54.589058,9.68,53,9.50,1198.75
219,220,2025-05-15,8106,GIBF1,Global IME Balanced Fund-1,10.36,10.41,10.21,10.36,192100,1987771.00,10.34,10.72,8.00,2025-05-15T14:56:36.589458,10.36,27,10.34,1062.69
224,225,2025-05-15,8023,MMF1,Mega Mutual Fund -1,8.77,9.19,8.76,9.08,374130,3394063.20,8.94,9.72,7.02,2025-05-15T14:56:36.013281,9.09,66,9.07,1135.00
233,234,2025-05-15,8073,NICFC,NIC Asia Flexi CAP Fund,8.88,9.06,8.88,9.04,4800,43331.00,9.02,10.99,8.13,2025-05-15T14:38:10.258724,9.04,20,9.02,92.21
234,235,2025-05-15,8074,KDBY,Kumari Dhanabriddhi Yojana,9.33,9.40,9.33,9.38,7200,67263.50,9.39,11.00,8.51,2025-05-15T14:55:08.588231,9.38,36,9.34,37.52
250,251,2025-05-15,9154,SFEF,Sunrise Focused Equity Fund,9.39,9.59,9.39,9.58,800,7586.00,9.42,10.66,7.71,2025-05-15T14:45:08.071658,9.59,8,9.48,958.00
252,253,2025-05-15,8125,NSIF2,NMB Sulav Investment Fund - 2,10.39,10.40,10.39,10.40,950,9875.00,10.37,12.47,9.34,2025-05-15T14:48:32.793179,10.40,5,10.39,1269.84
256,257,2025-05-15,9138,NIBLGF,NIBL Growth Fund,8.45,8.79,8.45,8.76,13400,117269.00,8.62,10.64,7.84,2025-05-15T14:57:05.788102,8.79,9,8.75,1156.32
257,258,2025-05-15,9139,SAGF,Sanima Growth Fund,9.46,9.69,9.46,9.68,235600,2278567.00,9.64,10.93,8.44,2025-05-15T14:59:44.008268,9.69,11,9.67,651.01
265,267,2025-05-15,9174,PRSF,Prabhu Smart Fund,10.64,10.65,10.64,10.64,110000,1170500.00,10.62,11.30,8.46,2025-05-15T14:13:46.119337,10.64,7,10.64,1064.00
266,268,2025-05-15,9178,RMF2,RBB Mutual Fund 2,9.43,9.43,9.30,9.40,500,4696.00,9.25,10.73,8.23,2025-05-15T14:37:00.898504,9.40,3,9.39,795.35
274,276,2025-05-15,9221,H8020,Himalayan 80-20,10.64,10.97,10.52,10.59,1010000,10629566.00,10.85,10.97,8.50,2025-05-15T14:59:54.291701,10.59,21,10.52,105.90
287,289,2025-05-15,9182,SIGS3,Siddhartha Investment Growth Scheme 3,10.01,10.20,10.01,10.19,31100,317130.00,10.12,10.81,8.28,2025-05-15T14:05:03.30126,10.19,9,10.19,821.11
289,291,2025-05-15,9191,C30MF,Citizens Super 30 Mutual Fund,9.40,9.58,9.22,9.39,22600,211764.00,9.57,10.92,8.13,2025-05-15T14:31:19.382903,9.39,12,9.37,704.93
293,295,2025-05-15,9198,LVF2,Laxmi Value Fund 2,9.50,9.51,9.50,9.51,5000,47502.00,9.50,10.40,7.84,2025-05-15T14:31:00.215823,9.51,9,9.50,760.80
306,308,2025-05-15,9241,KSY,Kumari Sabal Yojana,8.75,8.82,8.75,8.82,1200,10513.00,8.81,10.91,7.77,2025-05-15T13:41:28.551203,8.82,3,8.76,656.87
307,309,2025-05-15,9236,NICGF2,NIC ASIA Growth Fund-2,8.47,8.61,8.47,8.61,1500,12770.00,8.52,9.79,7.56,2025-05-15T14:43:24.738636,8.61,11,8.51,779.21
311,313,2025-05-15,9248,GSY,Garima Samriddhi Yojana,9.28,9.30,9.12,9.15,15500,141637.00,9.43,10.00,8.80,2025-05-15T14:51:45.832444,9.15,35,9.13,1143.75
314,316,2025-05-15,9244,NIBLSTF,NIBL Stable Fund,8.30,8.42,8.21,8.41,1650,13803.00,8.32,10.55,7.85,2025-05-15T14:59:48.298515,8.42,6,8.36,950.33
315,317,2025-05-15,9245,MNMF1,Muktinath Mutual Fund 1,9.21,9.30,9.11,9.18,13010,118800.00,9.39,10.42,8.67,2025-05-15T14:51:00.539337,9.18,20,9.13,1147.50
317,319,2025-05-15,9254,NMBHF2,NMB Hybrid Fund L- II,8.33,8.59,8.25,8.46,42690,356521.10,8.41,10.00,8.25,2025-05-15T14:59:36.422509,8.57,52,8.35,1154.65

In [22]:
mutual_f.shape

(36, 19)

In [23]:
mutual_=mutual_f[['Symbol','Open Price']]

In [24]:
mutual_

      Symbol  Open Price
120      SEF        9.89
136     NBF2        9.90
154    SIGS2       10.29
155     CMF2        9.39
156    NICBF        9.04
159      LUK        9.60
167     SLCF        9.61
170    NMB50       10.60
171     SFMF       10.22
181      KEF        8.86
183     SBCF        9.37
184      PSF       10.66
185   NIBSF2        8.06
204    NICSF        9.08
205     RMF1        9.10
208     NBF3        9.74
219    GIBF1       10.36
224     MMF1        8.77
233    NICFC        8.88
234     KDBY        9.33
250     SFEF        9.39
252    NSIF2       10.39
256   NIBLGF        8.45
257     SAGF        9.46
265     PRSF       10.64
266     RMF2        9.43
274    H8020       10.64
287    SIGS3       10.01
289    C30MF        9.40
293     LVF2        9.50
306      KSY        8.75
307   NICGF2        8.47
311      GSY        9.28
314  NIBLSTF        8.30
315    MNMF1        9.21
317   NMBHF2        8.33

In [25]:
ordinary_=net_ordinary_S[['Symbol','Open Price']]

In [26]:
ordinary_

     Symbol  Open Price
0      NIMB       204.1
1       SBI       380.0
2       EBL       614.1
3       MBL       211.0
4       LSL       204.0
..      ...         ...
309  SARBTM       869.9
310    GMLI      2650.0
313    NMIC      2050.0
316   CREST      2025.0
318    OMPL       578.3

[256 rows x 2 columns]

In [27]:
def SubIndex(debenture_,mutual_,ordinary_,shl_):
    i,j,k,l = 0,0,0,0
    for index, row in debenture_.iterrows():
        i += row['Open Price'] * 25
    for index, row in mutual_.iterrows():
        j += row['Open Price'] * 100
    for index, row in ordinary_.iterrows():
        k += row['Open Price'] * 10 
    for index, row in shl_.iterrows():
        l += row['Open Price'] * 100 
    
    return i,j,k,l

In [28]:
SubIndex(debenture_,mutual_,ordinary_,shl_)

(726492.5, 34040.0, 3021005.3, 52900.0)

In [29]:
net_total=sum(total(debenture_,mutual_,ordinary_,shl_))

In [30]:
net_total

3834437.8